name: Sanitize Config

on:
  push:
    branches:
      - main


jobs:
  sanitize:
    runs-on : ubuntu-latest
    steps:
      - uses: action/checkout@v3

      - name: Replace sensitive values with dumy
        run: |
          sed -i 's|public static final String URL = .*|public static final String URL = "jdbc:postgresql://dummy:5432/dump";|' src/banque/infrastructure/config/GlobalValue.java
          sed -i 's|public static final String USER = .*|public static final String USER = "dummyUser";|' src/banque/infrastructure/config/GlobalValue.java
          sed -i 's|public static final String PASSWORD = .*|public static final String PASSWORD = "dummyPass";|' src/banque/infrastructure/config/GlobalValue.java

      - name: Commit sanitized values
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -am "Sanitize GlobalValue.java"
          git push
